In [1]:
import os
import glob
import pandas as pd

In [2]:
csv_files = glob.glob('*.{}'.format('csv'))
csv_files

['AdaptiveHistogram.csv',
 'CovidAdaptiveHistogram.csv',
 'CovidHistogramEqualized.csv',
 'CovidImages.csv',
 'Images.csv',
 'NormalAdaptiveHistogram.csv',
 'NormalHistogramEqualized.csv',
 'NormalImages.csv']

In [ ]:
#Merging CovidAdaptiveHistogram+NormalAdaptiveHistogram

In [11]:
csv_files = glob.glob('*AdaptiveHistogram.{}'.format('csv'))
csv_files

['CovidAdaptiveHistogram.csv', 'NormalAdaptiveHistogram.csv']

In [12]:
df_concat = pd.concat([pd.read_csv(f) for f in csv_files ], ignore_index=True)
df_concat

,Column1,Column2,Column3,Column4,Column5,Column6,Column7,Column8,Column9,Column10,...,Column617,Column618,Column619,Column620,Column621,Column622,Column623,Column624,Column625,Label
0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,...,71.0,17.0,31.0,51.0,60.0,55.0,40.0,17.0,3.0,Covid
1,3.0,3.0,8.0,11.0,11.0,10.0,10.0,10.0,10.0,10.0,...,28.0,20.0,12.0,6.0,5.0,7.0,11.0,10.0,4.0,Covid
2,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,10.0,...,32.0,22.0,10.0,3.0,4.0,8.0,10.0,9.0,6.0,Covid
3,10.0,9.0,9.0,9.0,10.0,10.0,10.0,9.0,10.0,10.0,...,40.0,28.0,15.0,5.0,2.0,6.0,9.0,7.0,3.0,Covid
4,9.0,9.0,9.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,...,48.0,58.0,58.0,53.0,41.0,21.0,6.0,3.0,6.0,Covid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15937,55.0,55.0,151.0,173.0,153.0,183.0,208.0,214.0,242.0,223.0,...,203.0,205.0,197.0,164.0,153.0,180.0,175.0,110.0,96.0,Non-Covid
15938,69.0,71.0,58.0,62.0,148.0,161.0,145.0,155.0,162.0,185.0,...,203.0,200.0,214.0,209.0,170.0,160.0,193.0,88.0,92.0,Non-Covid
15939,62.0,61.0,50.0,122.0,155.0,147.0,183.0,221.0,228.0,226.0,...,201.0,200.0,201.0,198.0,183.0,164.0,183.0,64.0,81.0,Non-Covid
15940,65.0,62.0,53.0,130.0,157.0,157.0,194.0,223.0,222.0,227.0,...,195.0,202.0,217.0,208.0,204.0,173.0,175.0,145.0,47.0,Non-Covid
15941,153.0,179.0,218.0,217.0,218.0,214.0,198.0,228.0,238.0,240.0,...,220.0,220.0,216.0,240.0,218.0,218.0,246.0,227.0,198.0,Non-Covid

In [13]:
df_concat.to_csv('E:/project/AdaptiveHistogram.csv')

In [ ]:
#Merging CovidHistogramEqualized +NormalHistogramEqualized

In [3]:
csv_files = glob.glob('*HistogramEqualized.{}'.format('csv'))
csv_files

['CovidHistogramEqualized.csv', 'NormalHistogramEqualized.csv']

In [4]:
df_concat = pd.concat([pd.read_csv(f) for f in csv_files ], ignore_index=True)
df_concat

,Column1,Column2,Column3,Column4,Column5,Column6,Column7,Column8,Column9,Column10,...,Column617,Column618,Column619,Column620,Column621,Column622,Column623,Column624,Column625,Label
0,41.0,42.0,43.0,44.0,44.0,44.0,44.0,44.0,45.0,46.0,...,140.0,92.0,100.0,113.0,113.0,104.0,86.0,58.0,39.0,Covid
1,0.0,0.0,24.0,38.0,38.0,37.0,36.0,34.0,35.0,36.0,...,57.0,46.0,37.0,32.0,30.0,32.0,34.0,29.0,5.0,Covid
2,39.0,38.0,37.0,38.0,36.0,39.0,39.0,37.0,39.0,40.0,...,65.0,59.0,46.0,33.0,34.0,35.0,36.0,36.0,21.0,Covid
3,46.0,45.0,47.0,46.0,47.0,50.0,48.0,47.0,48.0,50.0,...,83.0,67.0,55.0,42.0,34.0,35.0,36.0,29.0,3.0,Covid
4,22.0,21.0,21.0,24.0,26.0,26.0,25.0,25.0,25.0,26.0,...,85.0,93.0,87.0,76.0,62.0,40.0,22.0,17.0,18.0,Covid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15937,4.0,10.0,134.0,160.0,145.0,178.0,208.0,218.0,247.0,227.0,...,205.0,205.0,198.0,171.0,162.0,180.0,179.0,118.0,92.0,Non-Covid
15938,10.0,14.0,4.0,24.0,143.0,163.0,148.0,156.0,163.0,186.0,...,207.0,203.0,217.0,210.0,176.0,160.0,187.0,72.0,86.0,Non-Covid
15939,11.0,10.0,8.0,115.0,174.0,165.0,193.0,229.0,233.0,230.0,...,216.0,214.0,213.0,208.0,195.0,175.0,182.0,43.0,89.0,Non-Covid
15940,11.0,7.0,9.0,123.0,176.0,172.0,202.0,231.0,227.0,231.0,...,213.0,217.0,226.0,213.0,204.0,180.0,185.0,139.0,29.0,Non-Covid
15941,164.0,184.0,215.0,212.0,206.0,198.0,195.0,227.0,237.0,241.0,...,218.0,224.0,215.0,243.0,227.0,230.0,250.0,239.0,224.0,Non-Covid

In [5]:
df_concat.to_csv('E:/project/HistogramEqualized.csv')